### ISSUE TITLE
Repeatedly outputs 6DOF data from first frame, data is incorrect

### ISSUE THREAD

**Issue by MrMho** [johnflux/python_trackir#1]
First off, thanks for putting together this library and making it public.

Here's my issue:

When I run your example from the readme:
```python
import tkinter
import time
from trackir import TrackIRDLL

trackrIr = TrackIRDLL(tkinter.Tk().wm_frame())
while True:
    data = trackrIr.NP_GetData()
    print(data)
    time.sleep(0.1)
```

I get the following output:
```
Loading DLL:  C:\Program Files (x86)\NaturalPoint\TrackIR5\NPClient64.dll
Loaded
NP_GetSignature says:
------------------
hardware camera
 software processing data
 track user movement

 Copyright EyeControl Technologies
precise head tracking
 put your head into the game
 now go look around

 Copyright EyeControl Technologies
------------------

Calling NP_RegisterWindowHandle
Calling NP_RequestData
Calling NP_RegisterProgramProfileID
Calling NP_StopCursor
Calling NP_StartDataTransmission
status: 0, frame: 0, cksum: 0, roll: 0, pitch: 0, yaw: 0, x: 0, y: 0, z: 0
status: 0, frame: 0, cksum: 0, roll: 0, pitch: 0, yaw: 0, x: 0, y: 0, z: 0
status: 0, frame: 0, cksum: 0, roll: 0, pitch: 0, yaw: 0, x: 0, y: 0, z: 0
status: 0, frame: 0, cksum: 0, roll: 0, pitch: 0, yaw: 0, x: 0, y: 0, z: 0
[and so on...]
```

It seems that the script repeatedly outputs 6DOF data from the same frame (`frame: 0`). In addition, the angles and coordinates are obviously incorrect. It tried Python versions 3.7.5 and 3.10, they both produce the same output.

The TrackIR GUI application (version 5.4.2) itself works flawlessly and detects all head movements.

Do you know why that is? Any idea how to fix this?

Thanks for your help.

**Comment by johnflux** [comment]
I have no idea, but perhaps try with an older version of the NPClient64.dll
lib?
It looks like they changed it so that we're supposed to ack the frame
somehow, otherwise it keeps resending it.

**Comment by MrMho** [comment]
Thanks for your reply. 
I went back from version 5.4.2 to 5.4.0 of the TrackIR software, as this is the oldest version that works with my TrackIR device. Unfortunately, this did not fix the problem.

**Comment by MrMho** [comment]
When I use an older version of the NPClient64.dll from the opentrack project (see link below), the Python script no longer repeatedly outputs values from the first frame and instead actually updates the frame. However,  the values for the angles and coordinates are still wrong, i.e., they all constantly remain 0, whereas the TrackIR software detects head movements correctly. 

https://github.com/opentrack/opentrack/tree/master/bin

**Comment by MrMho** [comment]
Updating the Games List (see button in the upper right corner of the TrackIR GUI) fixed the issue. The example from the readme (see above) is now working as expected and the 6DOF values seem to be plausible.
